### ISSUE TITLE
GPU를 이용한 학습 방법 문의

### ISSUE THREAD

**Issue by kittyLunar** [jaketae/koclip#7]
안녕하세요
KOCLIP을 이용하여 저희가 가지고 있는 데이터를 이용하여 학습을 시켜보려고 하는데
제공해주신 run.py, train.sh 를 이용해서 학습을 하면 
CPU만 사용을 합니다

`os.environ["CUDA_VISIBLE_DEVICES"]`
 혹은
`export CUDA_VISIBLE_DEVICES` 를 이용하여 지정을 해 준 후
학습을 하여도 GPU를 사용하지 않고 CPU만 사용을 하여 학습이 진행되고 있습니다.

GPU로 학습을 하는 방법이 따로 있는건지, 아니면 제가 소스를 수정해서 적용 되도록 변경 해야 하는건지
안내 부탁 드리겠습니다.

감사합니다.

**Comment by jaketae** [comment]
안녕하세요? 프로젝트 소스코드는 JAX/Flax와 TPU를 활용해 모델을 파인튜닝하는 용도로 작성되었습니다. 

프로젝트를 업데이트하지 않은지 오래되기도 해서 오늘 `koclip-base` 모델을 보다 용이한 torch로 포팅하는 작업을 진행했습니다.

```python
from transformers import AutoModel, AutoProcessor

model = AutoModel.from_pretrained("koclip/koclip-base-pt")
processor = AutoProcessor.from_pretrained("koclip/koclip-base-pt")
```

모델을 GPU로 옮기려면 

```
model = model.to("cuda")
```

처럼 해주시면 됩니다.

학습 코드는 커스텀으로 작성하셔도 되고, boilerplate을 선호하시면 [run_clip.py](https://github.com/huggingface/transformers/blob/main/examples/pytorch/contrastive-image-text/run_clip.py)을 사용하시면 될 것 같습니다. 

```
python run_clip.py --model_name_or_path koclip/koclip-base-pt ...
```

감사합니다.
